[colors.primary]
background = "#2d353b"
foreground = "#d3c6aa"

[colors.cursor]
text = "#2d353b"
cursor = "#d3c6aa"

[colors.vi_mode_cursor]
text = "#2d353b"
cursor = "#d3c6aa"

[colors.search.matches]
foreground = "#2d353b"
background = "#dbbc7f"

[colors.search.focused_match]
foreground = "#2d353b"
background = "#e67e80"

[colors.footer_bar]
foreground = "#2d353b"
background = "#d3c6aa"

[colors.selection]
text = "#2d353b"
background = "#d3c6aa"

[colors.normal]
black = "#475258"
red = "#e67e80"
green = "#a7c080"
yellow = "#dbbc7f"
blue = "#7fbbb3"
magenta = "#d699b6"
cyan = "#83c092"
white = "#d3c6aa"

[colors.bright]
black = "#475258"
red = "#e67e80"
green = "#a7c080"
yellow = "#dbbc7f"
blue = "#7fbbb3"
magenta = "#d699b6"
cyan = "#83c092"
white = "#d3c6aa"
